data:
  BaseUrl: https://www.insiderone.com
  Browser: chrome
  CareerButtonText: We're hiring
  FindJobButtonText: Find your dream job
  QaJobButtonText: Quality Assurance
  QaJobTitle: Quality Assurance
  DefaultLocation: Istanbul, Turkiye
  LeverUrl: https://jobs.lever.co/insiderone

gridConfiguration:
  gridURL: http://localhost:4444/
  isDebug: true
